# Generated by Django 5.2.17 on 2026-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(default='Other / Independent Specialty', max_length=100),
        ),
    ]
